networks:
  hydra_network:
    driver: bridge

services:
  # ✅ Hydra's Internal Flask App (Core)
  hydra_core:
    build: ./hydra_core
    container_name: hydra_core
    ports:
      - "5000:5000"
    env_file:
      - ./hydra_core/.env
    volumes:
      - ./logs:/var/log/hydra
    restart: unless-stopped
    networks:
      - hydra_network
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s  # Allow Flask to fully start before health check fails

  # ✅ Target Flask App (User-Provided)
  target_flask:
    build: ./target_flask
    container_name: target_flask
    ports:
      - "5050:5050"  # Ensure consistency inside and outside container
    env_file:
      - ./target_flask/.env
    volumes:
      - ./target_flask:/app
    restart: unless-stopped
    networks:
      - hydra_network
    depends_on:
      hydra_core:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5050/"]  # Check root instead of /health
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 320s  # Allow Flask app to fully start
    command: >
      /bin/sh -c "
      if [ -f /app/app.py ]; then 
        gunicorn --preload --timeout 90 -w 2 -b 0.0.0.0:5050 app:app;  
      else 
        echo '[❌] No app.py found in target_flask! Exiting...' && exit 1; 
      fi"


  # ✅ Redis for real-time log ingestion
  redis:
    image: redis:latest
    container_name: hydra_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - hydra_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 3

  # ✅ Data Pipeline (Processes logs from Redis)
  data_pipeline:
    build: ./data_pipeline
    container_name: hydra_data_pipeline
    restart: unless-stopped
    networks:
      - hydra_network
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - "8000:8000"

  # ✅ Prometheus for Metrics Collection
  prometheus:
    image: prom/prometheus:latest
    container_name: hydra_prometheus
    restart: unless-stopped
    networks:
      - hydra_network
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:9090/-/ready"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ✅ Grafana for Visualization
  grafana:
    image: grafana/grafana-oss:latest
    container_name: hydra_grafana
    restart: unless-stopped
    networks:
      - hydra_network
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/grafana_data:/var/lib/grafana
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ✅ cAdvisor for Container Resource Monitoring
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: hydra_cadvisor
    restart: unless-stopped
    networks:
      - hydra_network
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ✅ Machine Learning Model
  ml_model:
    build: ./ml_model
    container_name: hydra_ml_model
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - ./ml_model/.env
    volumes:
      - ./ml_model:/app
      - ./logs:/app/logs
      - ./ml_model/data:/app/data
    ports:
      - "8500:8500"
    restart: unless-stopped
    networks:
      - hydra_network
    command: ["python", "predict.py"]

volumes:
  redis_data:
  prometheus_data:
