global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'hydra_flask_app'
    static_configs:
      - targets: ['hydra_flask_app:5000']

  - job_name: 'flask_app_metrics'
    static_configs:
      - targets: ['hydra_flask_app:5000']

  - job_name: 'hydra_cadvisor'
    static_configs:
      - targets: ['hydra_cadvisor:8080']
